### ISSUE TITLE
change root node offset?

### ISSUE THREAD

**Issue by hopewise** [jpb12/react-tree-graph#41]
How would I change the offset of root node only?

**Comment by jpb12** [comment]
This isn't currently possible.

**Comment by jpb12** [comment]
As a workaround, you can do this using css:

```css
g:first-of-type text {
    transform: translate(0, 5px);
}
```
